name: Update Docker
on: 
  push:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.yml'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'  
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    if: true # false to skip job during debug
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    # despite the fact docker will build binary internally 
    # we want to stop workflow in case of any error before pushing to registry 
    - name: Get dependencies and Build
      run: |
        go version
        go mod download
        go build

    - name: Version strings
      id: version
      run: |
        echo "::set-output name=RELEASE_TIME::$(git show -s --format=%cI HEAD)"  

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        VERSION: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
        DATE: ${{ steps.version.outputs.RELEASE_TIME }}          
      with:
        name: cybertecpostgresql/pg_timetable
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: VERSION,COMMIT,DATE
