name: Release
on:
  release:
    types: [created]

jobs:

  goreleaser:
    if: true # false to skip job during debug
    runs-on: ubuntu-latest
    name: goreleaser
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  docker:
    if: true # false to skip job during debug
    runs-on: ubuntu-latest
    steps:
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Version strings
      id: version
      run: |
        echo "::set-output name=RELEASE_TIME::$(git show -s --format=%cI HEAD)"        

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        VERSION: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
        DATE: ${{ steps.version.outputs.RELEASE_TIME }}       
      with:
        name: cybertecpostgresql/pg_timetable
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: VERSION,COMMIT,DATE
        tag_semver: true